title: SecurEth
author: The SecurEth Foundation
description: Smart Contract Development Guidelines for Ethereum
url: "https://secureth.org/"
lang: en
timezone: UTC
includes: ["guidelines"]
exclude:
  - README.md
  - LICENSE
  - CNAME
  - .git*
